"""phase 3 ngo operations

Revision ID: d97a021906b5
Revises: fc7afecd543f
Create Date: 2026-06-30 22:12:28.397373+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97a021906b5'
down_revision: Union[str, None] = 'fc7afecd543f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend the existing report_status PG enum with the Phase 3 rescue
    # lifecycle states. ADD VALUE IF NOT EXISTS is idempotent; PG18 permits it
    # inside the migration transaction because the values aren't used here.
    new_statuses = [
        'volunteer_assigned', 'volunteer_accepted', 'on_route', 'reached_location',
        'rescue_completed', 'shelter_assigned', 'closed',
    ]
    for value in new_statuses:
        op.execute(f"ALTER TYPE report_status ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_attachments',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_attachments_report_id'), 'case_attachments', ['report_id'], unique=False)
    op.create_table('case_timeline_events',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_timeline_events_report_id'), 'case_timeline_events', ['report_id'], unique=False)
    op.create_index('ix_case_timeline_report_created', 'case_timeline_events', ['report_id', 'created_at'], unique=False)
    op.create_table('internal_notes',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notes_report_id'), 'internal_notes', ['report_id'], unique=False)
    op.create_table('volunteer_assignments',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'accepted', 'declined', 'completed', 'removed', name='assignment_status'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'volunteer_id', name='uq_assignment_report_volunteer')
    )
    op.create_index('ix_assignment_status', 'volunteer_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_volunteer_assignments_report_id'), 'volunteer_assignments', ['report_id'], unique=False)
    op.create_index(op.f('ix_volunteer_assignments_volunteer_id'), 'volunteer_assignments', ['volunteer_id'], unique=False)
    op.add_column('ngos', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('ngos', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('ngos', sa.Column('contact_phone', sa.String(length=32), nullable=True))
    op.add_column('ngos', sa.Column('operating_hours', sa.String(length=255), nullable=True))
    op.add_column('ngos', sa.Column('emergency_contact', sa.String(length=255), nullable=True))
    op.add_column('ngos', sa.Column('shelter_locations', sa.Text(), nullable=True))
    op.add_column('ngos', sa.Column('logo_key', sa.String(length=512), nullable=True))
    op.add_column('ngos', sa.Column('service_latitude', sa.Float(), nullable=True))
    op.add_column('ngos', sa.Column('service_longitude', sa.Float(), nullable=True))
    # NOT NULL columns get a server_default so existing rows backfill cleanly.
    op.add_column('ngos', sa.Column('service_radius_km', sa.Float(), nullable=False, server_default='25.0'))
    op.add_column('reports', sa.Column('children_present', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('reports', sa.Column('people_count', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('volunteers', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('volunteers', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('volunteers', sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('volunteers', sa.Column('completed_rescues', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('volunteers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('volunteers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('volunteers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'longitude')
    op.drop_column('volunteers', 'latitude')
    op.drop_column('volunteers', 'rating')
    op.drop_column('volunteers', 'completed_rescues')
    op.drop_column('volunteers', 'is_available')
    op.drop_column('volunteers', 'skills')
    op.drop_column('volunteers', 'phone')
    op.drop_column('reports', 'closed_at')
    op.drop_column('reports', 'claimed_at')
    op.drop_column('reports', 'people_count')
    op.drop_column('reports', 'children_present')
    op.drop_column('ngos', 'service_radius_km')
    op.drop_column('ngos', 'service_longitude')
    op.drop_column('ngos', 'service_latitude')
    op.drop_column('ngos', 'logo_key')
    op.drop_column('ngos', 'shelter_locations')
    op.drop_column('ngos', 'emergency_contact')
    op.drop_column('ngos', 'operating_hours')
    op.drop_column('ngos', 'contact_phone')
    op.drop_column('ngos', 'contact_email')
    op.drop_column('ngos', 'website')
    op.drop_index(op.f('ix_volunteer_assignments_volunteer_id'), table_name='volunteer_assignments')
    op.drop_index(op.f('ix_volunteer_assignments_report_id'), table_name='volunteer_assignments')
    op.drop_index('ix_assignment_status', table_name='volunteer_assignments')
    op.drop_table('volunteer_assignments')
    op.drop_index(op.f('ix_internal_notes_report_id'), table_name='internal_notes')
    op.drop_table('internal_notes')
    op.drop_index('ix_case_timeline_report_created', table_name='case_timeline_events')
    op.drop_index(op.f('ix_case_timeline_events_report_id'), table_name='case_timeline_events')
    op.drop_table('case_timeline_events')
    op.drop_index(op.f('ix_case_attachments_report_id'), table_name='case_attachments')
    op.drop_table('case_attachments')
    # ### end Alembic commands ###
