"""phase 4 volunteer admin

Revision ID: ef1bb0b48e09
Revises: d97a021906b5
Create Date: 2026-06-30 22:43:03.758768+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1bb0b48e09'
down_revision: Union[str, None] = 'd97a021906b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend assignment_status enum with the volunteer rescue-workflow states.
    for value in ['on_route', 'arrived', 'in_progress']:
        op.execute(f"ALTER TYPE assignment_status ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('everyone', 'ngo', 'volunteer', name='announcement_audience'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ngos', 'service_radius_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reports', 'children_present',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('volunteer_assignments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('volunteer_assignments', sa.Column('checklist', sa.Text(), nullable=True))
    op.add_column('volunteers', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('volunteers', sa.Column('languages', sa.Text(), nullable=True))
    op.add_column('volunteers', sa.Column('emergency_contact', sa.String(length=255), nullable=True))
    op.add_column('volunteers', sa.Column('working_radius_km', sa.Float(), nullable=True))
    op.add_column('volunteers', sa.Column('schedule', sa.Text(), nullable=True))
    op.add_column('volunteers', sa.Column('avatar_key', sa.String(length=512), nullable=True))
    op.add_column('volunteers', sa.Column('total_hours', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('volunteers', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('volunteers', 'completed_rescues',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteers', 'completed_rescues',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('volunteers', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('volunteers', 'total_hours')
    op.drop_column('volunteers', 'avatar_key')
    op.drop_column('volunteers', 'schedule')
    op.drop_column('volunteers', 'working_radius_km')
    op.drop_column('volunteers', 'emergency_contact')
    op.drop_column('volunteers', 'languages')
    op.drop_column('volunteers', 'certifications')
    op.drop_column('volunteer_assignments', 'checklist')
    op.drop_column('volunteer_assignments', 'notes')
    op.alter_column('reports', 'children_present',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ngos', 'service_radius_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'25'::double precision"),
               existing_nullable=False)
    op.drop_table('announcements')
    # ### end Alembic commands ###
